language: python

sudo: false

matrix:
  include:
    - python: 2.7
      env: DJANGO='dj111' CMS='cms36'

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install coverage isort tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PY_VER=py27; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)