name: Python application

on:
  push:
    branches: [ master, tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install pip<21
        pip install flake8 pytest
        pip install -r tests/requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=119 --statistics
    - name: Test with pytest
      run: |
        pytest -t tests
